export const services = [
  { slug: "digital-products", number: "01", title: "Digital Product Engineering", short: "Strategy, UX and engineering for platforms people rely on.", description: "We take ambitious ideas from product definition to resilient, production-ready software—combining sharp product thinking with senior engineering.", capabilities: ["Product strategy & discovery", "UX/UI systems", "Web application engineering", "API & platform architecture", "Quality assurance", "Continuous product delivery"] },
  { slug: "web-experiences", number: "02", title: "High-performance Websites", short: "Category-defining websites built to earn attention and demand.", description: "We turn positioning into fast, expressive digital experiences that tell a clear story and convert the right visitors into conversations.", capabilities: ["Digital strategy", "Information architecture", "Brand-led web design", "Next.js development", "CMS integration", "SEO & performance"] },
  { slug: "ai-automation", number: "03", title: "AI & Automation", short: "Practical AI systems that remove friction from real operations.", description: "We find the workflows where AI creates measurable leverage, then design secure automations your team can understand and operate.", capabilities: ["AI opportunity mapping", "Workflow automation", "Knowledge assistants", "LLM integrations", "Agentic systems", "Measurement & governance"] },
  { slug: "commerce-growth", number: "04", title: "Commerce & Growth Systems", short: "Connected customer journeys from acquisition to revenue.", description: "We design the infrastructure behind sustainable growth: commerce, payments, analytics, experimentation and lifecycle systems.", capabilities: ["E-commerce platforms", "Payments integration", "Conversion optimisation", "Analytics foundations", "CRM & lifecycle", "Growth experimentation"] },
] as const;

export const projects = [
  { slug: "schoolkit", title: "SchoolKit", category: "EdTech · SaaS platform", summary: "Reimagining how Nigerian schools run their daily operations.", impact: "One connected operating system", color: "#d7ff64", url: "schoolkit.ng", details: "A multi-tenant school management platform bringing attendance, fees, results, records and parent communication into one coherent experience.", services: ["Product strategy", "UX/UI design", "Platform engineering", "Payments"] },
  { slug: "betgenius", title: "BetGenius", category: "Sports intelligence · AI", summary: "Turning complex football data into a clear daily decision product.", impact: "50+ daily predictions", color: "#6b57ff", url: "betgenius.ng", details: "An AI-supported football intelligence platform with automated data enrichment, prediction categories, subscriptions and scalable publishing workflows.", services: ["Product engineering", "AI integration", "Data workflows", "Growth systems"] },
  { slug: "credo-catholica", title: "Credo Catholica", category: "Faith · Digital publishing", summary: "Building a structured home for timeless Catholic formation.", impact: "70+ content fields mapped", color: "#ef613f", url: "credocatholica.com", details: "A content-rich digital platform built around liturgical data, saints, prayers, formation pathways and structured publishing.", services: ["Content architecture", "Platform migration", "UX strategy", "Next.js engineering"] },
  { slug: "momentum-desk", title: "Momentum Desk", category: "Revenue operations · AI", summary: "A modern revenue operating system for growing businesses.", impact: "Lead-to-cash, unified", color: "#bce9ff", url: "momentumdesk.app", details: "A multi-currency revenue operations product connecting leads, quotes, invoices, payments and intelligent collections.", services: ["Product strategy", "Design systems", "SaaS engineering", "AI workflows"] },
] as const;

export const insights = [
  { slug: "why-digital-products-fail", tag: "Product strategy", title: "Why good digital products fail before engineering begins", excerpt: "The quiet strategic decisions that determine whether a product becomes useful, scalable and commercially viable.", date: "05 Oct 2026", read: "7 min" },
  { slug: "ai-automation-operating-model", tag: "AI & operations", title: "An operating model for AI automation that teams can trust", excerpt: "Move beyond demos: how to choose workflows, manage risk and measure the business value of applied AI.", date: "28 Sep 2026", read: "9 min" },
  { slug: "website-as-growth-system", tag: "Digital experience", title: "Your website is not a brochure. It is a growth system.", excerpt: "A practical framework for connecting positioning, user intent, proof and conversion into one coherent experience.", date: "19 Sep 2026", read: "6 min" },
] as const;

export const nav = [{ href: "/services", label: "Services" }, { href: "/work", label: "Work" }, { href: "/about", label: "Agency" }, { href: "/insights", label: "Insights" }] as const;
