export const services = [
  { slug: "digital-products", number: "01", title: "Digital Product Engineering", short: "Strategy, UX and engineering for platforms people rely on.", description: "We take ambitious ideas from product definition to resilient, production-ready software—combining sharp product thinking with senior engineering.", capabilities: ["Product strategy & discovery", "UX/UI systems", "Web application engineering", "API & platform architecture", "Quality assurance", "Continuous product delivery"] },
  { slug: "web-experiences", number: "02", title: "High-performance Websites", short: "Category-defining websites built to earn attention and demand.", description: "We turn positioning into fast, expressive digital experiences that tell a clear story and convert the right visitors into conversations.", capabilities: ["Digital strategy", "Information architecture", "Brand-led web design", "Next.js development", "CMS integration", "SEO & performance"] },
  { slug: "ai-automation", number: "03", title: "AI & Automation", short: "Practical AI systems that remove friction from real operations.", description: "We find the workflows where AI creates measurable leverage, then design secure automations your team can understand and operate.", capabilities: ["AI opportunity mapping", "Workflow automation", "Knowledge assistants", "LLM integrations", "Agentic systems", "Measurement & governance"] },
  { slug: "commerce-growth", number: "04", title: "Commerce & Growth Systems", short: "Connected customer journeys from acquisition to revenue.", description: "We design the infrastructure behind sustainable growth: commerce, payments, analytics, experimentation and lifecycle systems.", capabilities: ["E-commerce platforms", "Payments integration", "Conversion optimisation", "Analytics foundations", "CRM & lifecycle", "Growth experimentation"] },
] as const;

export const projects = [
  { slug: "ijmb", title: "IJMB.ng", category: "Education · Search growth", summary: "Building the definitive search destination for Nigeria’s IJMB pathway.", impact: "#1 organic position", color: "#d7ff64", url: "ijmb.ng", image: "/work/ijmb.png", details: "A focused education platform engineered around real candidate questions, technically sound information architecture and a search-led publishing system.", challenge: "Prospective students were searching with urgent, specific questions in a crowded and often confusing information landscape. IJMB.ng needed to become both the clearest answer and the most credible destination.", approach: "We aligned the site architecture with search intent, built tightly connected topic clusters, improved technical foundations and made every high-value page useful enough to deserve its position.", result: "IJMB.ng reached the number-one organic position for its priority search term. The work turned SEO from a collection of posts into a durable acquisition system.", services: ["SEO strategy", "Content architecture", "Technical SEO", "Web engineering"] },
  { slug: "schoolkit", title: "SchoolKit", category: "EdTech · SaaS platform", summary: "Reimagining how Nigerian schools run their daily operations.", impact: "One connected operating system", color: "#c9f353", url: "schoolkit.ng", image: "/work/schoolkit.png", details: "A multi-tenant school management platform bringing attendance, fees, results, records and parent communication into one coherent experience.", challenge: "School operations were fragmented across paper registers, spreadsheets and WhatsApp threads, with tools that rarely reflected Nigerian infrastructure or school workflows.", approach: "We shaped the product around six real user roles, designed offline-ready workflows, and connected payments, reporting, attendance and communication in one modular platform.", result: "SchoolKit launched as a clear, locally relevant category proposition: school management software built specifically for Nigerian private schools.", services: ["Product strategy", "UX/UI design", "Platform engineering", "Payments"] },
  { slug: "betgenius", title: "BetGenius", category: "Sports intelligence · AI", summary: "Turning complex football data into a clear daily decision product.", impact: "50+ daily predictions", color: "#6b57ff", url: "betgenius.ng", image: "/work/betgenius.png", details: "An AI-supported football intelligence platform with automated data enrichment, prediction categories, subscriptions and scalable publishing workflows.", challenge: "Dense match data needed to become fast, understandable guidance without hiding the uncertainty inherent in prediction.", approach: "We combined automated data workflows with a focused product hierarchy, clear confidence signals and a subscription-ready experience.", result: "A scalable intelligence product that can publish and organise more than 50 daily match predictions without overwhelming the user.", services: ["Product engineering", "AI integration", "Data workflows", "Growth systems"] },
  { slug: "credo-catholica", title: "Credo Catholica", category: "Faith · Digital publishing", summary: "Building a structured home for timeless Catholic formation.", impact: "70+ content fields mapped", color: "#ef613f", url: "credocatholica.com", image: "/work/credo-catholica.png", details: "A content-rich digital platform built around liturgical data, saints, prayers, formation pathways and structured publishing.", challenge: "A deep and interconnected body of material needed an information model that was rigorous without making the experience feel academic or difficult.", approach: "We mapped the content domain, designed repeatable publishing patterns and built navigation around how people actually explore faith and formation.", result: "A structured publishing foundation capable of carrying a large, interconnected library while keeping discovery calm and intuitive.", services: ["Content architecture", "Platform migration", "UX strategy", "Next.js engineering"] },
  { slug: "sailglobe-resource", title: "Sailglobe Resource", category: "Corporate · Energy services", summary: "Giving an ambitious resource company a more credible digital front door.", impact: "Clarity across every service", color: "#77c6ff", url: "sailgloberesourceltd.com", image: "/work/sailglobe.png", details: "A corporate web experience that translates broad operational capability into a clear, credible story for partners and decision-makers.", challenge: "The company needed to communicate a wide service range without sounding generic, while building confidence quickly with procurement and partnership audiences.", approach: "We simplified the offer, organised capabilities around buyer needs and created a visual language that feels established, precise and ready for larger opportunities.", result: "A focused corporate presence that makes the company easier to understand, assess and contact.", services: ["Positioning", "Information architecture", "Web design", "Development"] },
  { slug: "qleap-recruitment", title: "QLeap Recruitment", category: "Talent · Recruitment", summary: "Turning a recruitment service into a confident digital brand.", impact: "Candidate-to-client clarity", color: "#ff9d72", url: "qleaprecruitment.com.ng", image: "/work/qleap.png", details: "A recruitment website designed to serve two audiences clearly: organisations hiring high-quality talent and candidates looking for the right next move.", challenge: "Employers and candidates arrive with different needs. The experience had to create trust with both without splitting the brand in two.", approach: "We created distinct journeys, sharpened the messaging and designed conversion paths around vacancies, hiring enquiries and relationship building.", result: "A clearer recruitment proposition with purposeful journeys for both sides of the talent market.", services: ["Brand strategy", "UX/UI design", "Website development", "Conversion design"] },
  { slug: "momentum-desk", title: "Momentum Desk", category: "Revenue operations · AI", summary: "A modern revenue operating system for growing businesses.", impact: "Lead-to-cash, unified", color: "#bce9ff", url: "momentumdesk.app", image: "/work/momentum-desk.png", details: "A multi-currency revenue operations product connecting leads, quotes, invoices, payments and intelligent collections.", challenge: "Growing teams were managing one revenue journey across disconnected tools, creating duplicate work and weak visibility.", approach: "We designed a single operating model from lead to collection, then built modular workflows that keep the system understandable as teams scale.", result: "A coherent product foundation for managing pipeline, commercial documents, payments and follow-up in one place.", services: ["Product strategy", "Design systems", "SaaS engineering", "AI workflows"] },
] as const;

export const insights = [
  { slug: "how-to-choose-ai-automation-agency", tag: "AI automation", keyword: "AI automation agency", title: "How to choose an AI automation agency that can deliver real ROI", excerpt: "A practical buyer’s guide to use cases, security, integration, pricing and the evidence that separates production partners from demo builders.", date: "05 Oct 2026", read: "10 min", sections: [
    { heading: "Start with the operating problem, not the model", paragraphs: ["The best AI automation agency will ask where work stalls, where errors repeat and which decisions depend on scattered information before recommending a tool. A useful engagement starts with the economics of the workflow: volume, time, risk and the cost of delay.", "Be cautious when every answer is a chatbot. Customer support triage, document processing, lead qualification and internal knowledge retrieval have different failure modes. The system should fit the work."], bullets: ["A named workflow owner", "A measurable baseline", "Clear human-review rules", "A plan for exceptions"] },
    { heading: "What credible delivery looks like", paragraphs: ["A production partner should connect discovery, process design, engineering and adoption. That means mapping data sources, permissions and integrations before promising an outcome.", "Ask to see how the team evaluates outputs, monitors quality and handles sensitive data. Reliable automation is not a one-off build; it is an operating system with feedback loops."], bullets: ["Architecture and integration plan", "Evaluation criteria before launch", "Security and access controls", "Monitoring, support and iteration"] },
    { heading: "How AI automation agency pricing works", paragraphs: ["Pricing usually reflects workflow complexity, integration depth, data quality and the consequences of failure. A small, bounded pilot should prove value before a larger rollout.", "Compare proposals by the business outcome and ongoing operating cost—not only the initial build fee. The cheapest prototype can become expensive if nobody can maintain or trust it."] },
  ] },
  { slug: "digital-product-development-process", tag: "Product strategy", keyword: "digital product development agency", title: "The digital product development process: from risky idea to reliable launch", excerpt: "A seven-stage process for reducing uncertainty, making better product decisions and shipping software people can rely on.", date: "28 Sep 2026", read: "9 min", sections: [
    { heading: "A product process should reduce uncertainty", paragraphs: ["Digital product development is not a straight line from requirements to code. It is a sequence of decisions about the customer, the business model, the experience and the technical system.", "The strongest teams address the riskiest assumption first. That can mean testing demand before building, prototyping a difficult workflow or validating an integration before polishing the interface."], bullets: ["Frame the opportunity", "Map users and jobs", "Prototype critical journeys", "Validate technical risk", "Build the smallest coherent release", "Measure behaviour", "Iterate from evidence"] },
    { heading: "Why integrated teams move faster", paragraphs: ["When strategy, design and engineering work as separate hand-offs, important context disappears. An integrated digital product agency lets commercial goals, user evidence and technical constraints shape the same decision.", "Speed comes from fewer avoidable decisions—not from skipping discovery, quality assurance or architecture."] },
    { heading: "What to define before development", paragraphs: ["Agree on the user outcome, the commercial outcome and the evidence that will show progress. Then define what the first release will deliberately not do.", "A clear product boundary protects budget and gives the team a launch they can learn from rather than an endless backlog."] },
  ] },
  { slug: "custom-web-development-agency-guide", tag: "Web engineering", keyword: "custom web development agency", title: "When to hire a custom web development agency—and when not to", excerpt: "How to decide between templates, no-code tools and custom engineering without overspending or limiting what comes next.", date: "19 Sep 2026", read: "8 min", sections: [
    { heading: "Custom is valuable when the constraint is real", paragraphs: ["A custom web development agency makes sense when your business depends on a distinctive workflow, deep integration, demanding performance or a brand experience that templates cannot support.", "If the requirement is a simple brochure site with standard content, a mature template may be the better investment. The important decision is not custom versus off-the-shelf in principle; it is where differentiation creates value."], bullets: ["Complex customer journeys", "Payments or operational integrations", "Role-based platforms", "High performance and SEO requirements", "A reusable design system"] },
    { heading: "What to look for in an agency", paragraphs: ["Review the thinking behind the work, not only screenshots. Good partners can explain the problem, the trade-offs and the result in plain language.", "Ask how the team manages accessibility, performance, analytics, content and post-launch ownership. These are core parts of the product, not launch-week extras."] },
    { heading: "The questions that improve every proposal", paragraphs: ["Share the business outcome, real constraints, required integrations and internal owners. Ask each agency what it would validate first and what it would remove from the initial scope.", "A strong answer should make the path clearer before any code is written."] },
  ] },
  { slug: "why-digital-products-fail", tag: "Product strategy", keyword: "why digital products fail", title: "Why good digital products fail before engineering begins", excerpt: "The strategic decisions that determine whether a product becomes useful, scalable and commercially viable.", date: "12 Sep 2026", read: "7 min", sections: [
    { heading: "The failure usually starts with an untested assumption", paragraphs: ["Teams often treat a confident internal opinion as customer evidence. The roadmap grows, engineering begins and the first real test arrives after the expensive decisions are already fixed.", "Product discovery should expose the assumptions that could invalidate the investment and create the fastest responsible way to test them."] },
    { heading: "Activity is not progress", paragraphs: ["More screens, features and tickets can hide the absence of a useful outcome. Progress is reduced uncertainty and improved customer behaviour.", "Choose a small set of measures that connect adoption to commercial value. Make them visible throughout delivery."], bullets: ["A specific user behaviour", "A measurable business effect", "A quality or reliability threshold"] },
    { heading: "Build one coherent release", paragraphs: ["A good first release is not every requested feature in miniature. It is the smallest experience that solves one meaningful problem end to end.", "That coherence creates trust, produces cleaner evidence and gives the next investment a stronger basis."] },
  ] },
  { slug: "website-as-growth-system", tag: "Digital experience", keyword: "web development agency", title: "Your website is not a brochure. It is a growth system.", excerpt: "A framework for connecting positioning, search intent, proof and conversion into one coherent website.", date: "04 Sep 2026", read: "7 min", sections: [
    { heading: "A high-performance website has a job", paragraphs: ["A company website should help the right people understand your value, believe your evidence and take the next useful step. Visual polish matters, but it cannot compensate for unclear positioning or weak proof.", "Treat each important page as part of a journey: discovery through search or referral, evaluation through substance, and conversion through a relevant call to action."] },
    { heading: "Connect search demand to the sales story", paragraphs: ["SEO works best when it reflects the questions buyers already ask. Service pages should own commercial topics while articles answer the deeper questions that appear earlier in the decision.", "Internal links then move readers from education to evidence and from evidence to action without forcing the journey."] },
    { heading: "Measure the system after launch", paragraphs: ["Track qualified enquiries, high-intent page journeys and conversion points—not only page views. Search Console and analytics should reveal where demand enters, where attention drops and which proof moves a visitor forward.", "The launch is the beginning of optimisation. The system becomes more valuable as evidence sharpens the next iteration."] },
  ] },
] as const;

export const nav = [{ href: "/services", label: "Services" }, { href: "/work", label: "Work" }, { href: "/about", label: "Agency" }, { href: "/insights", label: "Insights" }] as const;
