import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CtaBand, PageIntro } from "@/components/site-shell";
import { services } from "@/lib/site";

const seo = {
  "digital-products": { keyword: "digital product development agency", title: "Digital Product Development Agency", description: "Product strategy, UX design and senior engineering for scalable SaaS platforms and custom digital products.", heading: "A digital product development agency for ambitious ideas.", copy: "From discovery to launch, we reduce product risk and turn complex requirements into useful, scalable software. Strategy, design and engineering work as one senior team." },
  "web-experiences": { keyword: "web development agency", title: "High-Performance Web Development Agency", description: "Strategy, web design, Next.js development and technical SEO for fast websites built to generate qualified demand.", heading: "Websites engineered to rank, persuade and convert.", copy: "We combine positioning, conversion-focused UX, high-performance development and technical SEO to build websites that work as measurable growth systems." },
  "ai-automation": { keyword: "AI automation agency", title: "AI Automation Agency", description: "Secure AI automation, workflow systems, knowledge assistants and LLM integrations designed around measurable business outcomes.", heading: "Practical AI automation built around real operations.", copy: "We identify high-value workflows, integrate the right models and data, and build human-controlled systems that save time without introducing invisible risk." },
  "commerce-growth": { keyword: "ecommerce development agency", title: "Commerce & Growth Systems Agency", description: "Ecommerce development, payments, analytics, CRM and conversion systems that connect acquisition to recurring revenue.", heading: "Commerce infrastructure built for sustainable growth.", copy: "We connect storefronts, payments, analytics and lifecycle journeys so customers encounter one coherent experience and teams get clearer revenue data." },
} as const;

export function generateStaticParams() { return services.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = services.find((item) => item.slug === slug); const page = seo[slug as keyof typeof seo]; return service && page ? { title: page.title, description: page.description, keywords: [page.keyword, service.title, "Nexagen Digital"], alternates: { canonical: `/services/${slug}` }, openGraph: { title: page.title, description: page.description } } : {}; }

export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const service = services.find((item) => item.slug === slug); const page = seo[slug as keyof typeof seo]; if (!service || !page) notFound();
  const schema = { "@context": "https://schema.org", "@type": "Service", name: page.title, description: page.description, provider: { "@type": "Organization", name: "Nexagen Digital", url: "https://nexagen.digital" }, areaServed: "Worldwide" };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><PageIntro eyebrow={`Service ${service.number} · ${page.keyword}`} title={service.title} lead={page.description} /><section className="section"><div className="shell detail-grid"><p className="eyebrow">What we bring</p><div><h2 className="service-seo-heading">{page.heading}</h2><p className="service-seo-copy">{page.copy}</p><div className="capability-grid" style={{ marginTop: 60 }}>{service.capabilities.map((capability, index) => <div key={capability}>0{index + 1} &nbsp; {capability}</div>)}</div></div></div></section><section className="section dark-section"><div className="shell detail-grid"><p className="eyebrow light">The outcome</p><div><h2>Useful from day one. Built to remain useful on day one thousand.</h2><p className="service-outcome">Every engagement is shaped around a measurable business result, a maintainable technical foundation and an experience people can use with confidence.</p></div></div></section><CtaBand /></>;
}
