import Link from "next/link";
import Image from "next/image";
import { nav } from "@/lib/site";

export function Logo() { return <Link href="/" className="logo" aria-label="Nexagen home"><Image src="/brand/nexagen-logo-light.png" alt="Nexagen" width={694} height={277} priority /></Link>; }
export function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <span aria-hidden="true">{diagonal ? "↗" : "→"}</span>; }
export function Header() { return <header className="header"><div className="shell nav-wrap"><Logo /><nav aria-label="Primary navigation">{nav.map((item) => <Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><Link href="/contact" className="button button-small header-cta">Start a project <Arrow diagonal /></Link><details className="mobile-menu"><summary><span className="menu-label">Menu</span><span className="menu-close">Close</span><i/><i/></summary><div className="mobile-menu-panel"><nav aria-label="Mobile navigation">{nav.map((item,index) => <Link key={item.href} href={item.href}><span>0{index+1}</span>{item.label}<Arrow diagonal /></Link>)}<Link href="/contact" className="mobile-menu-cta"><span>05</span>Start a project<Arrow diagonal /></Link></nav><div className="mobile-menu-foot"><a href="mailto:enquiry@nexagen.digital">enquiry@nexagen.digital</a><a href="https://www.instagram.com/nexagen_digital?stkn=MTg1c3pqd2Vzb3lmdw==" target="_blank" rel="noreferrer">Instagram ↗</a></div></div></details></div></header>; }
export function Footer() { return <footer className="footer"><div className="shell"><div className="footer-top"><div><p className="eyebrow light">Have a serious idea?</p><h2>Let’s build what’s next.</h2><Link href="/contact" className="text-link light">Start a conversation <Arrow diagonal /></Link></div><div className="footer-links"><div><p>Explore</p>{nav.map((x)=><Link key={x.href} href={x.href}>{x.label}</Link>)}<Link href="/careers">Careers</Link></div><div><p>Connect</p><a href="mailto:enquiry@nexagen.digital">enquiry@nexagen.digital</a><a href="mailto:hello@nexagen.digital">hello@nexagen.digital</a><a href="https://www.instagram.com/nexagen_digital?stkn=MTg1c3pqd2Vzb3lmdw==" target="_blank" rel="noreferrer">Instagram ↗</a></div></div></div><div className="footer-bottom"><Logo /><span>© {new Date().getFullYear()} Nexagen Digital.</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></div></footer>; }
export function PageIntro({ eyebrow, title, lead }: { eyebrow: string; title: string; lead: string }) { return <section className="page-intro"><div className="shell"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-lead">{lead}</p></div></section>; }
export function CtaBand() { return <section className="cta-band"><div className="shell cta-grid"><p className="eyebrow">A better digital future starts with a clear next move.</p><h2>Bring us the hard problem.</h2><Link className="button dark" href="/contact">Start a project <Arrow diagonal /></Link></div></section>; }
